repository:
  name: holo-nixpkgs
  description: Modules, packages and profiles that drive Holo, Holochain, and HoloPortOS
  topics: holo, holochain, nix, nixos
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: develop
  allow_merge_commit: true
  allow_squash_merge: false
  allow_rebase_merge: false

collaborators: []

teams:
  - name: central
    permission: push
  - name: happy
    permission: push
  - name: hydra
    permission: push

branches:
  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - Hydra
      enforce_admins: false
      restrictions:
        users:
          - peeech
          - filalex77
        teams: []
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - Hydra
      enforce_admins: true
      restrictions:
        users:
          - peeech
          - filalex77
        teams: []
  - name: hydra
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - Hydra
      enforce_admins: true
      restrictions:
        users:
          - peeech
          - filalex77
        teams: []
